// <auto-generated />
using System;
using GigGuide.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GigGuide.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241216085955_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GigGuide.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PerformanceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Green Day",
                            Description = "The american rock band is going on tour for their new album!",
                            Title = "The Saviors Tour"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "GHOST",
                            Description = "GHOST is on a world tour and want you to join!",
                            Title = "World Tour 2025"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Billie Eilish",
                            Description = "",
                            Title = "Hit me hard and soft: the tour"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Sabrina Carpenter",
                            Description = "",
                            Title = "Short n´Sweet Tour"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "The Offspring",
                            Description = "Following their eleventh studio album, The Offspring is going on tour! ",
                            Title = "Supercharged Worldwide in ´25"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Imagine Dragons",
                            Description = "Imagine Dragons are back on tour!",
                            Title = "LOOM World Tour"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Iron Maiden",
                            Description = "Iron Maiden are back on tour!",
                            Title = "Run for Your Lives World Tour"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "OneRepublic",
                            Description = "OneRepublic is going on tour!",
                            Title = "Escape To Europe 2025"
                        });
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "johanna@datababes.se",
                            FirstName = "Johanna",
                            LastName = "Gull",
                            Password = "Datababesftw123",
                            Phone = "070-6093654"
                        },
                        new
                        {
                            Id = 2,
                            Email = "caroline@datababes.se",
                            FirstName = "Caroline",
                            LastName = "Swanpalmer",
                            Password = "Bosslady123",
                            Phone = "070-1234567"
                        });
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformanceTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("int");

                    b.Property<int>("TicketsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.HasIndex("VenueId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcertId = 1,
                            PerformanceTime = new DateTime(2025, 6, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 895,
                            TicketsAvailable = 8000,
                            VenueId = 9
                        },
                        new
                        {
                            Id = 2,
                            ConcertId = 1,
                            PerformanceTime = new DateTime(2025, 6, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1200,
                            TicketsAvailable = 10000,
                            VenueId = 8
                        },
                        new
                        {
                            Id = 3,
                            ConcertId = 1,
                            PerformanceTime = new DateTime(2025, 6, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 895,
                            TicketsAvailable = 7000,
                            VenueId = 10
                        },
                        new
                        {
                            Id = 4,
                            ConcertId = 2,
                            PerformanceTime = new DateTime(2025, 5, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 895,
                            TicketsAvailable = 6000,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 5,
                            ConcertId = 2,
                            PerformanceTime = new DateTime(2025, 5, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 895,
                            TicketsAvailable = 8000,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 6,
                            ConcertId = 2,
                            PerformanceTime = new DateTime(2025, 5, 17, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 895,
                            TicketsAvailable = 10000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 7,
                            ConcertId = 3,
                            PerformanceTime = new DateTime(2025, 4, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1295,
                            TicketsAvailable = 60000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 8,
                            ConcertId = 3,
                            PerformanceTime = new DateTime(2025, 4, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1295,
                            TicketsAvailable = 60000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 9,
                            ConcertId = 3,
                            PerformanceTime = new DateTime(2025, 4, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1295,
                            TicketsAvailable = 35000,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 10,
                            ConcertId = 3,
                            PerformanceTime = new DateTime(2025, 4, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1295,
                            TicketsAvailable = 35000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 11,
                            ConcertId = 4,
                            PerformanceTime = new DateTime(2025, 4, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 60000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 12,
                            ConcertId = 4,
                            PerformanceTime = new DateTime(2025, 4, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 60000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 13,
                            ConcertId = 4,
                            PerformanceTime = new DateTime(2025, 3, 30, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 35000,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 14,
                            ConcertId = 4,
                            PerformanceTime = new DateTime(2025, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 35000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 15,
                            ConcertId = 4,
                            PerformanceTime = new DateTime(2025, 4, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 35000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 16,
                            ConcertId = 5,
                            PerformanceTime = new DateTime(2025, 10, 9, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 20000,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 17,
                            ConcertId = 5,
                            PerformanceTime = new DateTime(2025, 10, 10, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 20000,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 18,
                            ConcertId = 6,
                            PerformanceTime = new DateTime(2025, 6, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1095,
                            TicketsAvailable = 40000,
                            VenueId = 11
                        },
                        new
                        {
                            Id = 19,
                            ConcertId = 7,
                            PerformanceTime = new DateTime(2025, 6, 12, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1495,
                            TicketsAvailable = 40000,
                            VenueId = 11
                        },
                        new
                        {
                            Id = 20,
                            ConcertId = 7,
                            PerformanceTime = new DateTime(2025, 6, 13, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1495,
                            TicketsAvailable = 40000,
                            VenueId = 11
                        },
                        new
                        {
                            Id = 21,
                            ConcertId = 7,
                            PerformanceTime = new DateTime(2025, 6, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1495,
                            TicketsAvailable = 40000,
                            VenueId = 12
                        },
                        new
                        {
                            Id = 22,
                            ConcertId = 7,
                            PerformanceTime = new DateTime(2025, 6, 9, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1495,
                            TicketsAvailable = 40000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 23,
                            ConcertId = 8,
                            PerformanceTime = new DateTime(2025, 10, 31, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1195,
                            TicketsAvailable = 40000,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 24,
                            ConcertId = 8,
                            PerformanceTime = new DateTime(2025, 10, 30, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1195,
                            TicketsAvailable = 40000,
                            VenueId = 7
                        },
                        new
                        {
                            Id = 25,
                            ConcertId = 8,
                            PerformanceTime = new DateTime(2025, 11, 1, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TicketPrice = 1195,
                            TicketsAvailable = 40000,
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Arenavägen 35",
                            City = "Stockholm",
                            Country = "Sweden",
                            Name = "Avicii Arena"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Arenavägen 35",
                            City = "Stockholm",
                            Country = "Sweden",
                            Name = "Hovet"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gumpekullavägen 1",
                            City = "Linköping",
                            Country = "Sweden",
                            Name = "Saab Arena"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Arenavägen 4",
                            City = "Sandviken",
                            Country = "Sweden",
                            Name = "Göransson Arena"
                        },
                        new
                        {
                            Id = 5,
                            Address = "John Strandrupsvei 16",
                            City = "Oslo",
                            Country = "Norway",
                            Name = "Unity Arena"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nordenskiöldinkatu 11-13",
                            City = "Helsinki",
                            Country = "Finland",
                            Name = "Helsinki Jäähalli"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Hannemanns Allé 18-20",
                            City = "Copenhagen",
                            Country = "Denmark",
                            Name = "Royal Arena"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ekebergsletta",
                            City = "Oslo",
                            Country = "Norway",
                            Name = "Tons of Rock"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Gärdet",
                            City = "Stockholm",
                            Country = "Sweden",
                            Name = "STHLM Fields"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Tusindårsskoven",
                            City = "Falen, Odense V",
                            Country = "Denmark",
                            Name = "Tinderbox"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Arenaslingan 14",
                            City = "Stockholm",
                            Country = "Sweden",
                            Name = "Tele2 Arena"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Stiklestadveien 2",
                            City = "Trondheim",
                            Country = "Norway",
                            Name = "Bryggeribyen - EC Dahls Arena"
                        });
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Booking", b =>
                {
                    b.HasOne("GigGuide.Data.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GigGuide.Data.Entities.Performance", "Performance")
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Performance", b =>
                {
                    b.HasOne("GigGuide.Data.Entities.Concert", "Concert")
                        .WithMany("Performances")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GigGuide.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Concert", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("GigGuide.Data.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
